language: python
sudo: false
cache: pip

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27,flask,py27-django
  - python: 3.5
    env: TOXENV=py35,flask,py35-django
  - python: 3.6
    env: TOXENV=py36,flask,py36-django
  - python: 3.7
    env: TOXENV=py37,flask,py37-django

install:
  - pip install -U setuptools
  - pip install tox

script: tox

after_success:
  - TOXENV=codecov tox

notifications:
  email: false
