language: python
sudo: false
cache: pip

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27,flask
  - python: 3.6
    env: TOXENV=py36,flask,django,async
  - python: 3.7
    dist: xenial
    sudo: true
    env: TOXENV=py37,flask,django,async

install:
  - pip install -U setuptools
  - pip install tox

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: tox

after_success:
  - TOXENV=codecov tox
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false

branches:
  except:
    - /wip-.*/
